//! Mesh-preview adapter reports.
//!
//! Meshes extracted from SDF samples are topology proposals, not boundary
//! representations. This module therefore records the sampled grid, scalar
//! lowering status, crossing-edge diagnostics, and explicit preview-only
//! topology status. Surface Nets and related contouring methods are useful
//! preview algorithms, but their primitive-float samples must not become exact
//! geometry without replay; see Gibson, "Constrained Elastic Surface Nets:
//! Generating Smooth Surfaces from Binary Segmented Data," MICCAI (1998), and
//! Yap, "Towards Exact Geometric Computation," *Computational Geometry* 7.1-2
//! (1997).

use fast_surface_nets::{SurfaceNetsBuffer, surface_nets};

use crate::sampling::{SdfGridSamplingReport, SdfSampleTopologyStatus};
use crate::status::{SdfFreshness, SdfMetricStatus};

/// Preview meshing backend named by the report.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SdfMeshPreviewBackend {
    /// Surface Nets style preview over a sampled scalar grid.
    SurfaceNets,
}

/// Provenance of normals attached to a preview mesh.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SdfPreviewNormalStatus {
    /// No normals were generated.
    NotGenerated,
    /// Normals would be finite-difference preview data only.
    PreviewFiniteDifference,
}

/// Preview vertex emitted by the Surface Nets adapter.
///
/// Positions and normals are primitive `f32` values returned by
/// `fast_surface_nets`. They are display/proposal data only; exact topology
/// consumers must replay against the retained SDF expression.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SdfPreviewVertex {
    /// Preview position in the exact grid frame lowered to `f32`.
    pub position: [f32; 3],
    /// Preview finite-difference normal from the adapter.
    pub normal: Option<[f32; 3]>,
}

/// Preview triangle over generated vertices.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SdfPreviewTriangle {
    /// Vertex indices in counter-clockwise adapter order.
    pub indices: [u32; 3],
}

/// Report returned by mesh-preview adapters.
#[derive(Clone, Debug, PartialEq)]
pub struct SdfMeshPreviewReport {
    /// Preview backend.
    pub backend: SdfMeshPreviewBackend,
    /// Metric claim of the source expression before scalar lowering.
    pub metric_status: SdfMetricStatus,
    /// Prepared-source freshness.
    pub freshness: SdfFreshness,
    /// Whether generated data may be consumed as topology evidence.
    pub topology_status: SdfSampleTopologyStatus,
    /// Normal provenance for generated vertices.
    pub normal_status: SdfPreviewNormalStatus,
    /// Grid-sampling report consumed by the preview adapter.
    pub grid_samples: SdfGridSamplingReport,
    /// Number of sampled grid edges whose endpoints straddle or touch zero.
    pub crossing_edge_count: usize,
    /// Number of preview vertices generated by this adapter.
    pub vertex_count: usize,
    /// Number of preview triangles generated by this adapter.
    pub triangle_count: usize,
    /// Preview vertices generated by the adapter.
    pub vertices: Vec<SdfPreviewVertex>,
    /// Preview triangle index rows generated by the adapter.
    pub triangles: Vec<SdfPreviewTriangle>,
    /// Count of generated vertices or triangles rejected for non-finite values.
    pub non_finite_output_count: usize,
}

impl SdfMeshPreviewReport {
    /// Build a preview-only Surface Nets report from grid samples.
    ///
    /// The implementation uses `fast_surface_nets` as a numerical proposal
    /// engine. Generated vertices, normals, and triangles are retained as
    /// primitive-float preview data and the report remains `PreviewOnly`; this
    /// follows Gibson's Surface Nets contouring idea while preserving Yap's
    /// requirement that topology decisions replay through exact predicates.
    pub fn surface_nets_diagnostic(grid_samples: SdfGridSamplingReport) -> Self {
        let crossing_edge_count = count_crossing_edges(&grid_samples);
        let (vertices, triangles, normal_status, non_finite_output_count) =
            generate_surface_nets_preview(&grid_samples);
        let vertex_count = vertices.len();
        let triangle_count = triangles.len();
        Self {
            backend: SdfMeshPreviewBackend::SurfaceNets,
            metric_status: grid_samples.samples.metric_status,
            freshness: grid_samples.samples.freshness,
            topology_status: SdfSampleTopologyStatus::PreviewOnly,
            normal_status,
            grid_samples,
            crossing_edge_count,
            vertex_count,
            triangle_count,
            vertices,
            triangles,
            non_finite_output_count,
        }
    }

    /// Validate summary fields against the contained preview sampling report.
    pub fn is_self_consistent(&self) -> bool {
        self.grid_samples.is_self_consistent()
            && matches!(self.topology_status, SdfSampleTopologyStatus::PreviewOnly)
            && self.crossing_edge_count == count_crossing_edges(&self.grid_samples)
            && self.vertex_count == self.vertices.len()
            && self.triangle_count == self.triangles.len()
            && self.triangles.iter().all(|triangle| {
                triangle.indices.iter().all(|index| {
                    usize::try_from(*index).is_ok_and(|index| index < self.vertices.len())
                })
            })
            && (self.vertex_count > 0
                || matches!(self.normal_status, SdfPreviewNormalStatus::NotGenerated))
    }
}

fn generate_surface_nets_preview(
    report: &SdfGridSamplingReport,
) -> (
    Vec<SdfPreviewVertex>,
    Vec<SdfPreviewTriangle>,
    SdfPreviewNormalStatus,
    usize,
) {
    let [nx, ny, nz] = report.grid.dimensions;
    if nx < 2 || ny < 2 || nz < 2 {
        return (
            Vec::new(),
            Vec::new(),
            SdfPreviewNormalStatus::NotGenerated,
            0,
        );
    }
    if report.samples.non_finite_count > 0 {
        return (
            Vec::new(),
            Vec::new(),
            SdfPreviewNormalStatus::NotGenerated,
            report.samples.non_finite_count,
        );
    }
    if grid_point_count_u32(nx, ny, nz).is_none() {
        return (
            Vec::new(),
            Vec::new(),
            SdfPreviewNormalStatus::NotGenerated,
            0,
        );
    }

    let field_values = report
        .samples
        .samples
        .iter()
        .map(|sample| sample.value.unwrap_or(0.0) as f32)
        .collect::<Vec<_>>();
    let shape = GridShape { nx, ny, nz };
    let mut buffer = SurfaceNetsBuffer::default();
    surface_nets(
        &field_values,
        &shape,
        [0, 0, 0],
        [nx - 1, ny - 1, nz - 1],
        &mut buffer,
    );

    let origin = [
        report.grid.origin.x.to_f32_lossy(),
        report.grid.origin.y.to_f32_lossy(),
        report.grid.origin.z.to_f32_lossy(),
    ];
    let step = [
        report.grid.step.x.to_f32_lossy(),
        report.grid.step.y.to_f32_lossy(),
        report.grid.step.z.to_f32_lossy(),
    ];
    let (Some(origin), Some(step)) = (transpose_options(origin), transpose_options(step)) else {
        return (
            Vec::new(),
            Vec::new(),
            SdfPreviewNormalStatus::NotGenerated,
            buffer.positions.len() + buffer.indices.len() / 3,
        );
    };

    let mut non_finite_output_count = 0_usize;
    let mut vertices = Vec::with_capacity(buffer.positions.len());
    let mut index_map = vec![None; buffer.positions.len()];
    for (source_index, (position, normal)) in buffer
        .positions
        .iter()
        .zip(buffer.normals.iter())
        .enumerate()
    {
        let vertex = [
            origin[0] + position[0] * step[0],
            origin[1] + position[1] * step[1],
            origin[2] + position[2] * step[2],
        ];
        if !vertex.iter().all(|value| value.is_finite())
            || !normal.iter().all(|value| value.is_finite())
        {
            non_finite_output_count += 1;
            continue;
        }
        let mapped_index = u32::try_from(vertices.len()).ok();
        vertices.push(SdfPreviewVertex {
            position: vertex,
            normal: Some(*normal),
        });
        index_map[source_index] = mapped_index;
    }

    let mut triangles = Vec::with_capacity(buffer.indices.len() / 3);
    for triangle in buffer.indices.chunks_exact(3) {
        let a = mapped_index(triangle[0], &index_map);
        let b = mapped_index(triangle[1], &index_map);
        let c = mapped_index(triangle[2], &index_map);
        if let (Some(a), Some(b), Some(c)) = (a, b, c) {
            triangles.push(SdfPreviewTriangle { indices: [a, b, c] });
        } else {
            non_finite_output_count += 1;
        }
    }

    let normal_status = if vertices.is_empty() {
        SdfPreviewNormalStatus::NotGenerated
    } else {
        SdfPreviewNormalStatus::PreviewFiniteDifference
    };
    (vertices, triangles, normal_status, non_finite_output_count)
}

fn mapped_index(index: u32, index_map: &[Option<u32>]) -> Option<u32> {
    usize::try_from(index)
        .ok()
        .and_then(|index| index_map.get(index).copied().flatten())
}

fn grid_point_count_u32(nx: u32, ny: u32, nz: u32) -> Option<u32> {
    nx.checked_mul(ny)?.checked_mul(nz)
}

#[derive(Clone, Copy)]
struct GridShape {
    nx: u32,
    ny: u32,
    nz: u32,
}

impl fast_surface_nets::ndshape::Shape<3> for GridShape {
    type Coord = u32;

    fn as_array(&self) -> [Self::Coord; 3] {
        [self.nx, self.ny, self.nz]
    }

    fn size(&self) -> Self::Coord {
        self.nx * self.ny * self.nz
    }

    fn usize(&self) -> usize {
        (self.nx * self.ny * self.nz) as usize
    }

    fn linearize(&self, coords: [Self::Coord; 3]) -> u32 {
        let [x, y, z] = coords;
        (z * self.ny + y) * self.nx + x
    }

    fn delinearize(&self, index: u32) -> [Self::Coord; 3] {
        let x = index % self.nx;
        let yz = index / self.nx;
        let y = yz % self.ny;
        let z = yz / self.ny;
        [x, y, z]
    }
}

fn transpose_options(values: [Option<f32>; 3]) -> Option<[f32; 3]> {
    Some([values[0]?, values[1]?, values[2]?])
}

fn count_crossing_edges(report: &SdfGridSamplingReport) -> usize {
    let [nx, ny, nz] = report.grid.dimensions;
    let nx = nx as usize;
    let ny = ny as usize;
    let nz = nz as usize;
    let values = &report.samples.samples;
    let mut count = 0_usize;
    for z in 0..nz {
        for y in 0..ny {
            for x in 0..nx {
                let index = grid_index(x, y, z, nx, ny);
                if x + 1 < nx
                    && crosses_zero(
                        values[index].value,
                        values[grid_index(x + 1, y, z, nx, ny)].value,
                    )
                {
                    count += 1;
                }
                if y + 1 < ny
                    && crosses_zero(
                        values[index].value,
                        values[grid_index(x, y + 1, z, nx, ny)].value,
                    )
                {
                    count += 1;
                }
                if z + 1 < nz
                    && crosses_zero(
                        values[index].value,
                        values[grid_index(x, y, z + 1, nx, ny)].value,
                    )
                {
                    count += 1;
                }
            }
        }
    }
    count
}

fn grid_index(x: usize, y: usize, z: usize, nx: usize, ny: usize) -> usize {
    x + nx * (y + ny * z)
}

fn crosses_zero(a: Option<f64>, b: Option<f64>) -> bool {
    let (Some(a), Some(b)) = (a, b) else {
        return false;
    };
    (a <= 0.0 && b >= 0.0) || (a >= 0.0 && b <= 0.0)
}
