//! Mesh-preview adapter reports.
//!
//! Meshes extracted from SDF samples are topology proposals, not boundary
//! representations. This module therefore records the sampled grid, scalar
//! lowering status, crossing-edge diagnostics, and explicit preview-only
//! topology status. Surface Nets and related contouring methods are useful
//! preview algorithms, but their primitive-float samples must not become exact
//! geometry without replay; see Gibson, "Constrained Elastic Surface Nets:
//! Generating Smooth Surfaces from Binary Segmented Data," MICCAI (1998), and
//! Yap, "Towards Exact Geometric Computation," *Computational Geometry* 7.1-2
//! (1997).

use crate::sampling::{SdfGridSamplingReport, SdfSampleTopologyStatus};
use crate::status::{SdfFreshness, SdfMetricStatus};

/// Preview meshing backend named by the report.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SdfMeshPreviewBackend {
    /// Surface Nets style preview over a sampled scalar grid.
    SurfaceNets,
}

/// Provenance of normals attached to a preview mesh.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SdfPreviewNormalStatus {
    /// No normals were generated.
    NotGenerated,
    /// Normals would be finite-difference preview data only.
    PreviewFiniteDifference,
}

/// Report returned by mesh-preview adapters.
#[derive(Clone, Debug, PartialEq)]
pub struct SdfMeshPreviewReport {
    /// Preview backend.
    pub backend: SdfMeshPreviewBackend,
    /// Metric claim of the source expression before scalar lowering.
    pub metric_status: SdfMetricStatus,
    /// Prepared-source freshness.
    pub freshness: SdfFreshness,
    /// Whether generated data may be consumed as topology evidence.
    pub topology_status: SdfSampleTopologyStatus,
    /// Normal provenance for generated vertices.
    pub normal_status: SdfPreviewNormalStatus,
    /// Grid-sampling report consumed by the preview adapter.
    pub grid_samples: SdfGridSamplingReport,
    /// Number of sampled grid edges whose endpoints straddle or touch zero.
    pub crossing_edge_count: usize,
    /// Number of preview vertices generated by this adapter.
    pub vertex_count: usize,
    /// Number of preview triangles generated by this adapter.
    pub triangle_count: usize,
}

impl SdfMeshPreviewReport {
    /// Build a preview-only Surface Nets diagnostic report from grid samples.
    ///
    /// This does not emit mesh vertices yet. It records the exact scalar-lower
    /// input and crossing-edge count so a future meshing backend can be wired
    /// without changing the topology contract.
    pub fn surface_nets_diagnostic(grid_samples: SdfGridSamplingReport) -> Self {
        let crossing_edge_count = count_crossing_edges(&grid_samples);
        Self {
            backend: SdfMeshPreviewBackend::SurfaceNets,
            metric_status: grid_samples.samples.metric_status,
            freshness: grid_samples.samples.freshness,
            topology_status: SdfSampleTopologyStatus::PreviewOnly,
            normal_status: SdfPreviewNormalStatus::NotGenerated,
            grid_samples,
            crossing_edge_count,
            vertex_count: 0,
            triangle_count: 0,
        }
    }
}

fn count_crossing_edges(report: &SdfGridSamplingReport) -> usize {
    let [nx, ny, nz] = report.grid.dimensions;
    let nx = nx as usize;
    let ny = ny as usize;
    let nz = nz as usize;
    let values = &report.samples.samples;
    let mut count = 0_usize;
    for z in 0..nz {
        for y in 0..ny {
            for x in 0..nx {
                let index = grid_index(x, y, z, nx, ny);
                if x + 1 < nx
                    && crosses_zero(
                        values[index].value,
                        values[grid_index(x + 1, y, z, nx, ny)].value,
                    )
                {
                    count += 1;
                }
                if y + 1 < ny
                    && crosses_zero(
                        values[index].value,
                        values[grid_index(x, y + 1, z, nx, ny)].value,
                    )
                {
                    count += 1;
                }
                if z + 1 < nz
                    && crosses_zero(
                        values[index].value,
                        values[grid_index(x, y, z + 1, nx, ny)].value,
                    )
                {
                    count += 1;
                }
            }
        }
    }
    count
}

fn grid_index(x: usize, y: usize, z: usize, nx: usize, ny: usize) -> usize {
    x + nx * (y + ny * z)
}

fn crosses_zero(a: Option<f64>, b: Option<f64>) -> bool {
    let (Some(a), Some(b)) = (a, b) else {
        return false;
    };
    (a <= 0.0 && b >= 0.0) || (a >= 0.0 && b <= 0.0)
}
